name: Deploy to Vercel

description: Deploy the frontend to Vercel

inputs:
  vercel_token:
    description: "Vercel token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
      run: |
        npm install -g vercel
        vercel --prod --token=$VERCEL_TOKEN