name: Deploy to Vercel

description: Deploy the frontend to Vercel

inputs:
  vercel_token:
    description: "Vercel token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Install dependencies
      run: cd frontend && npm install
      shell: bash

    - name: Build project
      run: cd frontend && npm run build
      shell: bash
    - name: Deploy to Vercel

      env:
        VERCEL_TOKEN: ${{ inputs.vercel_token }}
      run: |
        cd frontend && npm install -g vercel
        vercel --prod --token=$VERCEL_TOKEN --yes
      shell: bash
