services:
  catifier-backend:
    container_name: catifier-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: ./start.sh
    env_file: .env
    volumes:
      - ./catifier-service-account.json:/app/catifier-service-account.json
      - ./catifier.db:/app/catifier.db
      - ./src:/app/src
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/catifier-service-account.json
    ports:
      - 8000:8000
  catifier-frontend:
    container_name: catifier-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file: ./frontend/.env
    volumes:
      - ./frontend/public:/app/public
      - ./frontend/src:/app/src
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tailwind.config.ts:/app/tailwind.config.ts
      - ./frontend/postcss.config.mjs:/app/postcss.config.mjs
      - ./frontend/next.config.ts:/app/next.config.ts
      - ./frontend/eslint.config.mjs:/app/eslint.config.mjs
      - ./frontend/components.json:/app/components.json
    ports:
      - 3000:3000
