name: Terraform Plan

description: Terraform Plan

inputs:
  gcp_service_account_key:
    description: The GCP service account key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Authenticate to GCP
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/gcp-key.json
      run: |
        echo "${{ inputs.gcp_service_account_key }}" > $GOOGLE_APPLICATION_CREDENTIALS
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: cd terraform && terraform init
      shell: bash

    - name: Terraform Plan
      run: cd terraform && terraform plan
      shell: bash

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve
      shell: bash
