name: Terraform Plan

description: Terraform Plan

inputs:
  gcp_service_account_key:
    description: The GCP service account key
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3

    - name: Authenticate to GCP
      run: |
        echo "${{ inputs.gcp_service_account_key }}" | base64 -d > ${{ runner.temp }}/gcp-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=${{ runner.temp }}/gcp-key.json" >> $GITHUB_ENV
      shell: bash

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: cd terraform && terraform init
      shell: bash

    - name: Terraform Plan
      run: cd terraform && terraform plan
      shell: bash

    - name: Terraform Apply
      run: cd terraform && terraform apply -auto-approve
      shell: bash
