on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: |
          echo "VERSION=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)" >> $GITHUB_ENV

      - name: Set Terraform variable
        run: |
          echo "TF_VAR_image_version=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: ./.github/actions/docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_repo: catifier
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile.backend

      - name: Terraform
        uses: ./.github/actions/terraform
        with:
          gcp_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Vercel
        uses: ./.github/actions/vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
