on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        id: set_version
        run: |
          VERSION=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: ./.github/actions/docker-image
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_repo: catifier
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile.backend

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Test Python
        uses: ./.github/actions/test-python
        with:
          docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/catifier:${{ needs.build.outputs.version }}

  deploy-cloud-resources:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v4

      - name: Get version from build job
        run: |
          echo "VERSION=${{ needs.build.outputs.version }}" >> $GITHUB_ENV

      - name: Terraform
        uses: ./.github/actions/terraform
        with:
          gcp_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          image_version: ${{ needs.build.outputs.version }}

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: [deploy-cloud-resources]
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: ./.github/actions/vercel
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}

  send-discord-message:
    runs-on: ubuntu-latest
    needs: [deploy-cloud-resources, deploy-vercel]
    steps:
      - uses: actions/checkout@v4

      - name: Send Discord Message
        uses: ./.github/actions/discord-message
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "Catifier CI"
          embed-title: "Release"
          embed-description: "🚀 ${{ github.actor }} deployed `${{ github.repository }}.v${{ needs.build.outputs.version }}`"
          embed-color: 0x00A6FF
          embed-url: ${{ secrets.VERCEL_URL }}
          embed-footer-text: "Catifier"
